using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Imperial.Medieval.Praises;

namespace Content.Client.Imperial.Medieval.Praises;

[GenerateTypedNameReferences]
public sealed partial class PraiseWindow : DefaultWindow
{
    public Action<string>? OnSendButtonPressed;
    private const int MaxPraiseReasonLength = 50;

    public PraiseWindow()
    {
        RobustXamlLoader.Load(this);
        SendButton.OnPressed += _ =>
        {
            if (ReasonEdit.Text.Length > MaxPraiseReasonLength)
            {
                MessageLabel.Text = Loc.GetString("praises-window-toolong", ("length", MaxPraiseReasonLength));
                return;
            }
            OnSendButtonPressed?.Invoke(ReasonEdit.Text);
        };
    }

    public void Update(PraiseWindowMessage msg)
    {
        MessageLabel.Text = msg.Message;
        SendButton.Disabled = msg.SendButtonDisabled;
    }
}
