using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Linq;

namespace Content.Client.Imperial.Medieval.Praises;

[GenerateTypedNameReferences]
public sealed partial class PraiseRatingWindow : DefaultWindow
{
    public PraiseRatingWindow(IEnumerable<(string, int)> rating)
    {
        RobustXamlLoader.Load(this);

        rating = rating.OrderByDescending(p => p.Item2).ToList();

        foreach ((string name, int weight) in rating)
        {
            Label label = new Label
            {
                Text = $"{name} / {weight}",
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center
            };
            RecordContainer.AddChild(label);
        }
    }
}
