using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Imperial.Medieval.Praises;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Content.Client.Message;
using System.Numerics;

namespace Content.Client.Imperial.Medieval.Praises;

[GenerateTypedNameReferences]
public sealed partial class PraiseViewWindow : DefaultWindow
{
    public Action<PraiseViewRecord>? OnEditWeightButtonPressed;
    public Action<PraiseViewRecord>? OnDeleteButtonPressed;

    public PraiseViewWindow(List<PraiseViewRecord> praises, bool admin, bool spam, bool wait)
    {
        RobustXamlLoader.Load(this);

        if (wait)
        {
            RichTextLabel waitLabel = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            waitLabel.SetMarkup(Loc.GetString("praises-view-wait"));
            MainContainer.AddChild(waitLabel);
        }

        if (spam)
        {
            RichTextLabel spamWarnLabel = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            spamWarnLabel.SetMarkup(Loc.GetString("praises-view-spam"));
            MainContainer.AddChild(spamWarnLabel);
        }

        if (praises.Count == 0)
            return;

        LineEdit? weightEdit = null;
        if (admin)
        {
            BoxContainer weightEditBox = new()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
            MainContainer.AddChild(weightEditBox);

            weightEditBox.AddChild(new Label()
            {
                Text = Loc.GetString("praises-view-weightedit"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center
            });
            weightEdit = new()
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                MinSize = new Vector2(50, 0),
            };
            weightEditBox.AddChild(weightEdit);
        }

        foreach (PraiseViewRecord record in praises)
        {
            BoxContainer recordBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                VerticalExpand = true
            };
            RecordContainer.AddChild(recordBox);

            RichTextLabel label1 = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center
            };
            label1.SetMarkup(Loc.GetString("praises-view-fromdate", ("from", record.GivenByName), ("date", record.Date)));
            recordBox.AddChild(label1);

            Label label2 = new Label
            {
                Text = $"'{record.Reason}'",
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center
            };
            recordBox.AddChild(label2);

            RichTextLabel label3 = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center
            };
            label3.SetMarkup(Loc.GetString(record.Weight > 0 ? "praises-view-weightpositive" : "praises-view-weightnegative", ("weight", record.Weight)));
            recordBox.AddChild(label3);

            if (!admin)
                return;

            Button changeWeightButton = new()
            {
                Text = Loc.GetString("praises-view-weightbutton"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            changeWeightButton.OnPressed += _ =>
            {
                if (weightEdit == null || !int.TryParse(weightEdit.Text, out int newWeight))
                    return;

                record.Weight = newWeight;
                label3.SetMarkup(Loc.GetString(record.Weight > 0 ? "praises-view-weightpositive" : "praises-view-weightnegative", ("weight", record.Weight)));
                OnEditWeightButtonPressed?.Invoke(record);
            };
            recordBox.AddChild(changeWeightButton);

            ConfirmButton deleteButton = new()
            {
                Text = Loc.GetString("praises-view-delbutton"),
                ConfirmationText = Loc.GetString("praises-view-delbutton-confirm"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            deleteButton.OnPressed += _ =>
            {
                OnDeleteButtonPressed?.Invoke(record);
                recordBox.Dispose();
            };
            recordBox.AddChild(deleteButton);
        }
    }
}
