using Content.Client.Imperial.Medieval.Factions.UI.Elements;
using Content.Shared.Imperial.Medieval.Calendar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Calendar.Board;

[GenerateTypedNameReferences]
public sealed partial class CalendarBoardWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    public EntityUid Owner;

    public CalendarBoardWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TabContainer.SetTabTitle(WantedTab, Loc.GetString("calendar-board-tab-wanted"));
        TabContainer.SetTabTitle(CalendarTab, Loc.GetString("calendar-board-tab-calendar"));
        TabContainer.SetTabTitle(AnnouncementsTab, Loc.GetString("calendar-board-tab-announcements"));
    }

    public void Populate(CalendarBoardBoundUserInterfaceState state)
    {
        WantedGrid.RemoveAllChildren();

        foreach (var item in state.Wanted)
        {
            var entry = new WantedDeskEntry(item.Value);
            WantedGrid.AddChild(entry);
        }
    }
}
