using System.Globalization;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;

/// <summary>
/// Confirmation dialog shown to a faction leader who pressed War in the relations matrix.
/// It doubles as the reason input, so there is no separate confirm step on the button itself.
/// Uses MedievalWindow to match WarDeclaredWindow
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DeclareWarMenu : MedievalWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    /// <summary>
    /// Fires with the typed reason once the leader confirms. Never fires on cancel.
    /// </summary>
    public Action<string>? DeclarePressed;

    public DeclareWarMenu(ProtoId<MedievalFactionPrototype> userFaction, ProtoId<MedievalFactionPrototype> targetFaction)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var targetProto = _proto.Index(targetFaction);

        // Faction names in factions.yml are lowercase nouns, so they get title-cased
        var targetName = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(targetProto.Name);

        PromptLabel.SetMessage(Loc.GetString("faction-war-declare-prompt", ("faction", targetName)), defaultColor: targetProto.Color);
        AlliesLabel.SetMessage(Loc.GetString("faction-war-declare-allies-warning", ("faction", targetName)));

        // server re-clamps this anyway
        ReasonEdit.IsValid = text => text.Length <= DispatchWarEvent.MaxReasonLength;

        DeclareButton.OnPressed += _ =>
        {
            DeclarePressed?.Invoke(ReasonEdit.Text);
            Close();
        };

        CancelButton.OnPressed += _ => Close();
    }
}
