using System.Globalization;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;

/// <summary>
/// Unprompted popup telling the player that their faction is now at war, why, and how they were
/// dragged into it. Pushed by the server via <see cref="MedievalWarDeclaredEvent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WarDeclaredWindow : MedievalWindow
{
    public WarDeclaredWindow(MedievalWarDeclaredEvent ev)
    {
        RobustXamlLoader.Load(this);

        var proto = IoCManager.Resolve<IPrototypeManager>();
        var declarerProto = proto.Index(ev.Declarer);
        var targetProto = proto.Index(ev.Target);

        var declarer = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(declarerProto.Name);
        var target = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(targetProto.Name);

        var key = ev.Involvement switch
        {
            WarInvolvement.Declarer => "faction-war-declared-by-us",
            WarInvolvement.Target => "faction-war-declared-on-us",
            WarInvolvement.AllyOfDeclarer => "faction-war-ally-of-declarer",
            WarInvolvement.AllyOfTarget => "faction-war-ally-of-target",
            WarInvolvement.AllyOfBoth => "faction-war-ally-of-both",
            _ => "faction-war-declared-on-us"
        };

        HeadlineLabel.SetMessage(
            Loc.GetString(key, ("declarer", declarer), ("target", target)),
            defaultColor: proto.Index<FactionRelationsPrototype>("War").Color);

        var hasReason = !string.IsNullOrWhiteSpace(ev.Reason);
        ReasonHeaderLabel.Visible = hasReason;

        // reason OPTIONAL!!
        ReasonLabel.SetMessage(hasReason ? ev.Reason : Loc.GetString("faction-war-no-reason"));

        AcknowledgeButton.OnPressed += _ => Close();
    }
}
