using Content.Shared.Imperial.Medieval.Courier;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Courier;

[GenerateTypedNameReferences]
public sealed partial class LetterRecipientMenu : DefaultWindow
{
    public LetterRecipientMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(LetterRecipientBoundUserInterfaceState state)
    {
        Recipients.RemoveAllChildren();

        var (titleLoc, titleWithNameLoc, missingLoc) = state.Mode switch
        {
            LetterRecipientUiMode.Contract => (
                "merc-contract-target-window-title",
                "merc-contract-target-window-title-with-name",
                "merc-contract-target-missing"),
            _ => (
                "courier-letter-recipient-window-title",
                "courier-letter-recipient-window-title-with-name",
                "courier-letter-recipient-missing"),
        };

        Title = Loc.GetString(titleLoc);

        if (state.Recipient == null)
        {
            var emptyLabel = new RichTextLabel();
            emptyLabel.SetMessage(Loc.GetString(missingLoc));
            Recipients.AddChild(emptyLabel);
            return;
        }

        Title = Loc.GetString(titleWithNameLoc, ("name", state.Recipient.Profile.Name));
        Recipients.AddChild(new LetterRecipientEntry(state.Recipient));
    }
}
