using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Dogs;

[GenerateTypedNameReferences]
public sealed partial class WolfToDogOffer : DefaultWindow
{
    public event Action? OnApplyPressed;
    public event Action? OnRejectPressed;

    public WolfToDogOffer()
    {
        RobustXamlLoader.Load(this);

        ApplyButton.OnPressed += _ =>
        {
            OnApplyPressed?.Invoke();
            Close();
        };

        RejectButton.OnPressed += _ =>
        {
            OnRejectPressed?.Invoke();
            Close();
        };
    }
}
